/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf 
Author: Bruce Lima (https://sketchfab.com/bw.lima)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spalding-basket-ball-db5f9c28708142909b15212625a127f9
Title: Spalding Basket Ball
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.pSphere1_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[0, 0, -0.061]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.983, 0.967, 0.983]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
